### ISSUE TITLE
TRACKING: Issues for smaller terminal sizes down to 80x24 (columns x rows)

### ISSUE THREAD

**Issue by neiljp** [zulip/zulip-terminal#1005]
Known issues, in approximate priority order:
* [ ] 'All messages' is not accessible from a panel context
* [ ] Depending on user name/email and organization name/url, this can disappear from the top of the UI in small widths
* [ ] Message display is too narrow without autohide mode (manually) enabled
* [ ] Popups do not scale down appropriately if window sizes are adjusted #1008 
* [ ] Autohide: clicking on a message does not hide side panels [minor? mouse] 
* [x] Autohide: side panels not hidden when narrowing with shortcut keys (f/#/P) [fixed by #1100]
* [x] Help menu does not render properly (descriptions in left column are long and do not wrap) [fixed by #1018]

If you experience other issues, please add comments below.
