### ISSUE TITLE
TRACKING: Follow-up to black transition

### ISSUE THREAD

**Issue by neiljp** [zulip/zulip-terminal#1047]
* [ ] Add black 'badge' to README
* [ ] Document basic expected style (isort + black?)
* [ ] Document auto-fixing code at base level & editor integration
* [ ] Pre-commit hook?
* [ ] Migrate to zulint (may require updates to earlier categories)
* [ ] Consider deprecation of flake8 settings, use of autopep8, use of autoflake; use of pyflakes?

**Comment by andersk** [comment]
* [ ] Consider applying Black to `setup.py` and `tools/*`, which were initially excluded ([discussion](https://chat.zulip.org/#narrow/stream/206-zulip-terminal/topic/zulint.2Fblack.2Fisort/near/1198914)).

**Comment by neiljp** [comment]
#1192 resolves second point.

**Comment by neiljp** [comment]
Marking flake8 settings and similar as completed, since we have migrated to ruff.
