### ISSUE TITLE
TRACKING: Theme Related Issues

### ISSUE THREAD

**Issue by Rohitth007** [zulip/zulip-terminal#1069]
We have recently done theme restructuring when simplifies managing themes and opens up theme related issues and ideas to explore. 

- [ ] adding FAQ details for adding themes (recommended to discuss with the project rather than add custom ones individually)
- [ ] Add actual 24bit color codes to DefaultColor
- [ ] Move from `#rgb` - 216 colors to `hxxx` 256 color format
- [ ] Add all the official gruvbox colors into GruvboxColor. (Maybe also change gruvbox.py to gruvbox_dark.py?)
- [ ] Add new themes (solarized dark/light, gruvbox light, etc)
- [ ] Support external user-defined themes #1067
- [ ] Improve transparency handling #513
- [ ] Improve monochrome theme (add monochrome light?) #603 
- [ ] Improve handling of server stream colors (24bit support, tweak colors based on theme)
- [ ] Add color meta data to themes (pygments syntax highlighting colors #1012 , stream colors, etc)

**Comment by neiljp** [comment]
Not all of these items have been discussed sufficiently, so please chat on the #zulip-terminal stream on chat.zulip.org about them first to ensure we're going in the right direction :+1:
