### ISSUE TITLE
TRACKING: Emoji Picker popup improvements

### ISSUE THREAD

**Issue by zee-bit** [zulip/zulip-terminal#1121]
We recently added support for reacting to messages with Emojis (other than the previously `:thumbs_up:`), ending at 19f1396. This was a combined effort of multiple contributors and multiple PR's (#913, #707). We decided to go with a simpler logic for now and add improvements later. Here's a list of UI/UX improvements that need to be worked upon:

- [ ] **Highlight the reacted emoji in the list of original+aliases** - e.g. for emoji `+1, thumbs_up, like`, if `thumbs_up` is the reacted emoji, then highlight it similar to how we do in footer autocomplete - `+1, <thumbs_up>, like`
- [ ] **Allow reacting with aliases as well** - Currently, we only allow reacting with original emojis (the first one in the list of original+aliases), unless the message was already reacted with an alias by others. We want users to be able to react with aliases of an emoji as well. e.g. for `+1, thumbs_up, like`, the user could further select any one from these to react with, not just `+1`.
- [ ] **Update the EmojiPicker popup on reaction events**: This should be fairly straightforward, because we already update the underlying data-structure (i.e.`model.active_emoji_data`) on reaction event. The only thing left is to update and render the EmojiPicker popup on reaction events optimally.
- [ ] **Group emojis into different categories similar to the web app**: The web app groups the emojis into categories namely (Popular, Smileys & Emoticons, People and body, etc), though this is not much of a high-priority right now, but there are users who would really want that sort of distinction in ZT too.

**Comment by zulipbot** [comment]
Hello @zulip/server-emoji members, this issue was labeled with the "area: emoji" label, so you may want to check it out!
