### ISSUE TITLE
TRACKING: Add remaining type annotations to tests

### ISSUE THREAD

**Issue by neiljp** [zulip/zulip-terminal#1229]
This was started in Summer 2021 and is now mostly complete (exclusions are in `pyproject.toml`) 🎉 

Remaining exclusions are now in `pyproject.toml`:
- [ ] `model/test_model.py`
- [ ] `ui/test_ui_tools.py`
- [ ] `ui_tools/test_messages.py`

If taking up elements of this, you will need to examine test files that are annotated for comparison and add them to one file at a time, enabling checking by removing the related exclusion.

**Updated to translate into a tracking issue and removal personal tagging**

**Comment by zulipbot** [comment]
Hello @zulip/server-refactoring members, this issue was labeled with the "area: refactoring" label, so you may want to check it out!

**Comment by plugyawn** [comment]
@neiljp Could you explain this a little further? I'd like to take this up.

**Comment by DaveOkpare** [comment]
@zulipbot claim

**Comment by zulipbot** [comment]
Hello @DaveOkpare!

Thanks for your interest in Zulip! You have attempted to claim an issue without the label "help wanted". You can only claim and submit pull requests for issues with the [help wanted](https://github.com/zulip/zulip-terminal/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee+label%3A%22help+wanted%22) label.

If this is your first time here, we recommend reading our [guide for new contributors](https://zulip.readthedocs.io/en/latest/overview/contributing.html) before getting started.

**Comment by neiljp** [comment]
@DaveOkpare Apologies for the slow response, but either file should be good - though both are quite large! If you wish to take this up, you might wish to follow #1337, which is specific to another file, but could provide useful directions.
