### ISSUE TITLE
TRACKING: PR Template improvements

### ISSUE THREAD

**Issue by neiljp** [zulip/zulip-terminal#1360]
I merged #1357 after a little feedback, and I think this may get more indirect feedback by how it ends up getting used instead. From that PR, we may want to track:

- [ ] Is the 'Outstanding Aspects' section obvious enough in prompting what to fill in?
- [ ] Is it sufficiently obvious how to use the 'External discussions & connections' section?
- [ ] Do existing/new contributors both find these changes an improvement?
- [ ] Is the self-review checklist useful?
- [ ] Are the use of each set of checkboxes clear? (for who, when to use them)
