### ISSUE TITLE
Check bounds & warn users re various supported versions (platform/python/server/client)

### ISSUE THREAD

**Issue by neiljp** [zulip/zulip-terminal#1436]
The current values of these are shown in the About popup at runtime:
- [ ] Platform (Linux/MacOS/[Unsupported])
- [ ] Python version/implementation (3.x, x=...; implementation=CPython, PyPy)
- [ ] Zulip server version (and feature level - ZFL in code)
- [ ] Zulip-terminal version

It would useful to warn users if these are outside of the 'supported' bounds, in various locations:
- upon startup on the console?
- upon startup in some kind of popup if very important?
- upon startup in the footer if less important?
- highlighted in the About popup?

'Supported' is currently defined via documentation, based on testing in CI (platform, python) and constraints on installs (python version) - and in the past we aimed to define a minimum server via a version in `version.py` (which some tests use). We can improve the use of these, and use them to warn or error in case of certain issues.

In addition to static values, certain checks require runtime connections:
- any specified/connected server (version); checking from this data shouldn't require prompting the user
- the latest cloud/self-hosted server release & latest zulip-terminal release; this should be an option for background checks, or require active selection by the user

Prompts could take various forms, and inspiration from those used in the web app or mobile would be useful where applicable. Examples could include
- warnings
  - unsupported platform/python/... - but may still work! please report success!
  - server is definitely not supported; use at your own risk (error?)
  - features missing (list known ones?)
- errors
  - a version is known to be insecure, or very out of date
- prompts to upgrade, and how/where (securely)

**Please discuss this in #zulip-terminal before proceeding, as this issue may need refinement first**

**Comment by neiljp** [comment]
One element of this is #704, which is an earlier version of this idea focused only on server version.
