### ISSUE TITLE
Migrate from 'Stream' to 'Channel' naming

### ISSUE THREAD

**Issue by neiljp** [zulip/zulip-terminal#1510]
### Client terminology migration description

Like other migrations of this type, this should eventually include updating:
- [ ] User-visible UI
- [ ] Documentation
- [ ] Any API usage
- [ ] Terminology internal to the application

The substitution in each case should be fairly straightforward, however for this migration it is important to
- [ ] confirm at which Zulip feature level the Server (web app) made this change (see the API changelog)
- [ ] ensure the UI shows the appropriate term based on the server (zulip) feature level (ZFL in our source), so using an older server will look similar to the web app and mobile
- [ ] update the documentation to 'Channel', but possibly add a FAQ entry for the renaming? (eg. mismatch between UI & docs?
- [ ] only use any updated API language after the associated feature level at which they were introduced (which may be different to the UI change ZFL)

Resources for this migration:
- zulip/zulip-mobile#5830

The Documentation is not dynamic (outside the application), so we can 

- [ ] 
- [ ] 
- [ ] - [ ] 

### When was this feature first available in Zulip?
If you know:
- **Zulip version:**
  (eg. 2.1, 5.0, 8.0, ..., or 'Zulip Cloud today')
- **Zulip feature level:**
  (see https://zulip.com/api/changelog)
