### ISSUE TITLE
Review & improve ordering of autocomplete (users/mentions)

### ISSUE THREAD

**Issue by neiljp** [zulip/zulip-terminal#1526]
### Description of feature missing from other Zulip clients

While a more keyboard-focused client, our user autocomplete could benefit from aspects found in other clients:
(web, and recently flutter zulip/zulip-flutter#692 zulip/zulip-flutter#693 zulip/zulip-flutter#608)
- [ ] Prioritizing users in the current topic (then stream?), like we do with users in a DM conversation
- [ ] Prioritizing users which have recent DMs
- [ ] Prioritizing real users over bots?

This likely should include at least mentions within the body of a message, but potentially other user prioritization elsewhere (to discuss).

Each of these will require understanding and potentially upgrading the internal data structures that store this data, and ensuring it is up to date - which may not be present already.

**Comment by sauravk58** [comment]
assign me
