### ISSUE TITLE
TRACKING: Extend user documentation

### ISSUE THREAD

**Issue by amanagr** [zulip/zulip-terminal#26]
- [ ] Supported Features
- [x] List of common problems with solution
- [ ] A working demo of ZT. ( An image / video )
- [ ] Why use ZT?
- [ ] How to run on windows? ( urwid uses`fcntl` library which is not available on non-unix platforms.) Recommend using WSL.

**Comment by timabbott** [comment]
I assume this is user documentation?

We should include some developer documentation as well, that points out we're using urwid and where the best docs for that are.

**Comment by kurianbenoy** [comment]
@amanagr @timabbott , I was intrested to write a user documentation for Zulip Terminal.

Please suggest topics to be added for User documentation Zulip-terminal and where should the documentation be and ?

**Comment by amanagr** [comment]
How about starting with the content we have in our Readme?

**Comment by kurianbenoy** [comment]
Ya @amanagr  .What all are you planning to include in Readme?

**Comment by neiljp** [comment]
I've extended this to be a tracking issue for now, focusing on extending user documentation.

Regarding "supported features", this could be a rather long list to handle. What we likely want are notes as to what features we have that are:
* missing, compared to webapp (and maybe mobile)? (#731)
* motivational (see "Why use ZT" below)
* different from the others through choice (eg. `z`, marking read); this is partially in the FAQ
* different from the others through platform requirements (eg. TUI vs GUI, keyboard vs mouse vs touch)

The latter two of these are covered by #547.

I've marked the problems+solutions checkbox, as by now we have `docs/FAQ.md` for frequently asked questions, which we can update as more arise.

We have a screenshot in the README now (#286), but we have discussed having a range of tutorial-like pages showing recordings of activities users may want to perform, and this is probably covered by #221 now.

The "Why use ZT" question is at least partially answered by a recent change to the README, where I added an **About** section.

Regarding how to run on Windows, we now have WSL1/2 support indicated in the README (https://github.com/zulip/zulip-terminal#supported-platforms), though do still have #357 for tracking this problem more generally. Given we have documentation on this, the latter issue should be sufficient.

**Comment by ankur0904** [comment]
@neiljp I want to work on this issue.

**Comment by neiljp** [comment]
@ankur0904 This is a tracking issue, and is mostly split out into other issues at this point.

Do you have a specific aspect you'd like to work on, or that you see is missing?

**Comment by ankur0904** [comment]
@neiljp I want to work on 
- `A working demo of ZT. ( An image / video )` part.

Thanks

**Comment by neiljp** [comment]
Supported features are not explicitly listed but should be covered by #731 

A screenshot is included in the main README, and we now have a user tutorial. The FAQ and tutorial include various screenshots and animations to indicate how features work.

"Why use ZT" is covered by the description and introduction section in the README.

The Windows support is currently documented in the FAQ (https://github.com/zulip/zulip-terminal/blob/main/docs/FAQ.md#what-operating-systems-are-supported) with #357 noted concerning windows-native support, which urwid may now allow in some way.

Since this covers the original motivations for this point, I'm going to close this issue now. Updated smaller aspects should be in specific issues related to https://github.com/zulip/zulip-terminal/labels/area%3A%20documentation, though I may split that into user and development documentation.
