### ISSUE TITLE
TRACKING: Typeahead improvements

### ISSUE THREAD

**Issue by sumanthvrao** [zulip/zulip-terminal#448]
With the v1 implementation of #441 merged, here are a few followups in store :

- [x] Indicating the options one has to auto-complete in the footer (After user pressed `ctrl + f`) (fixed in #540)
- [x] Going back to the previous auto-complete. (fixed in #532)
- [x] Handling conflicts when 2 users have the same full name. (Possibly using `@**Name|User_id**` or email to distinguish) (fixed in #928)
- [x] Prioritizing mentions to users in the current narrow. (Eg: People who are subscribed to stream/narrow) (fixed in #730)
- [ ] Editing the 'starred' version (`#**test here**`) and autocompleting it further. (Place the cursor before last 2 stars
- [x] Auto complete emoji names in message content. (fixed in #525)
- [x] Support Group-autocomplete (Eg: `@*terminal*`)
- [x] Support topic typeahead in topic box (fixed in #, with spaces in #823)
- [x] Support topic stream+topic typeahead in message composition (fixed in #1004)
- [x] Allow spaces in autocomplete to work fully in composition (fixed in stream/topic boxes in #823) 
- [x] Support typeahead completion after eg. parentheses (fix #541)

Related ideas:
- [ ] Adjust layout of footer text to indicate text matching against results, separation between result parts, ...

**Comment by sumanthvrao** [comment]
Update: We support group-autcomplete through e6972b0066946f35461e19bc1c238644767ba084 and 5 after

**Comment by kaustubh-nair** [comment]
Update: Going back to previous autocomplete added through 74369b197bcce46e57266bde8d22550cf4cf47bc

**Comment by sumanthvrao** [comment]
Update: We support auto-completing emoji names with 150a0fafd4f98700dfffce9ff3adfb69b379e049 and one after.

**Comment by kaustubh-nair** [comment]
Mentioning the emoji download issue here https://github.com/zulip/zulip-terminal/issues/558

**Comment by kaustubh-nair** [comment]
Follow-up: Add support to automatically show typeahead suggestions based on prefix string triggers.

**Comment by neiljp** [comment]
Once #540 is merged, we can consider adjustments to the `[more]` text, to improve indications of how many there are (beyond 10) or maybe how to show the rest - if we don't find an alternative solution to this such as a scrolling footer.

**Comment by kaustubh-nair** [comment]
#732 for improving ordering of group typeaheads

**Comment by Ezio-Sarthak** [comment]
Add-on to the list: Auto complete time mentions in message content (#894)

**Comment by neiljp** [comment]
I'm closing this now, as the bulk of typeahead (ie. autocomplete) is implemented, with remaining improvements indicated as separate issues, tagged with `area: autocomplete`.

Regarding entries in the description: #899 covers the remaining entry in the list, while #1164 covers the note at the bottom.
