### ISSUE TITLE
TRACKING: Support further editing of topic titles

### ISSUE THREAD

**Issue by neiljp** [zulip/zulip-terminal#451]
There are multiple elements to this issue:
 - [x] A) editing topics of messages is possible after a server-specified time-limit; currently we don't allow any editing after the time limit (just relax the editing constraint?)
 - [x] B) when editing a message topic we should ask users somehow if they wish to edit just the current message topic, or subsequent messages too (replies)
 - [x] C) we should support editing full topic titles (support by editing in topic view?)

**Comment by neiljp** [comment]
Particularly (C) is high priority, to allow us to rename full topics within ZT.
A related bug is that if a topic is renamed in the webapp, we don't handle updating the topic list @sumanthvrao

**Comment by kaustubh-nair** [comment]
I should also mention that we're missing community topic editing support.

**Comment by neiljp** [comment]
@kaustubh-nair This seems to have been mostly completed with #675, and I think #785 will fix the bug I mentioned above. 
Community editing, and the general allowance for editing of `(no topic)` topics, seem like the remaining elements of this?

**Comment by neiljp** [comment]
@kaustubh-nair Just to confirm, but the basic topic editing appears to be complete after the work from the Summer?
So this leaves the community topic editing and no-topic editing?

**Comment by kaustubh-nair** [comment]
@neiljp Yes, that's correct

**Comment by neiljp** [comment]
@kaustubh-nair Thanks for confirming :+1: I'm closing this and have broken out the remaining work into #836 (community) and #837 (no topic). If you have any branches then they can be assigned to close those issues independently.
