### ISSUE TITLE
TRACKING: Message rendering bugs/enhancements

### ISSUE THREAD

**Issue by neiljp** [zulip/zulip-terminal#452]
- [ ] #402 : quoting (other cases may be present)
- [ ] Render horizontal rulers
- [ ] Render tables
- [ ] #415 Ascii images
- [ ] #359 PR: Images in the default browser
- [ ] #424 PR: Messages links popup menu
- [ ] #397 PR: Viewing a message in the browser

**Comment by preetmishra** [comment]
Update: `4: List links at end of message (and/or in popup?)` has been resolved in #703 and #708.

**Comment by zee-bit** [comment]
Update: The last point (`Add a key to view a message in the browser`) has been resolved through #991.
