### ISSUE TITLE
TRACKING: Message search followups to #430

### ISSUE THREAD

**Issue by sumanthvrao** [zulip/zulip-terminal#458]
With #430, we now alter message search to search for messages in current narrow. This means, if you are in a PM narrow and use `/` to search for messages, we only display results of messages, belonging to that narrow itself. Here are some followups which are possible now that 430 is in place.

Most of the followup here is from brainstorming here - https://chat.zulip.org/#narrow/stream/206-zulip-terminal/topic/clear.20search.20text/near/767819.

- [ ] Currently, using `z` (or similar) on a search results message, *exits* out of the search narrow. The correct behaviour a user might want it to maintain search in this stream as well. Then the problem of when to exit search arises. Some discussions we had involved having an explicit key to exit search. 
- [ ] A likely discussion is when to *clear* the search text in UI. This can be coupled with when we 'exit' search. 
- [ ] The current version of `get_msg_ids_in_current_narrow` had been updated (bugfix) for handling search results and the conditional has been moved up to prevent other narrows from matching. However, it is still below `all messages` narrow, `[ ]`. This would be a potential #FIXME when we move to a different design like ['home', 'view'] for default narrow.
