### ISSUE TITLE
TRACKING: Table rendering enhancements

### ISSUE THREAD

**Issue by preetmishra** [zulip/zulip-terminal#582]
With #550 merged, we now support rendering for tables in `zulip-term (ZT)`.  The mentioned PR inscribes the building blocks for the support, however, there's still room for refinements. 

- [ ] Support inline-table styles.
- [ ] Support multi-line cells.
- [ ] Introduce a mechanism to handle tables for narrow screens (tricky).

**Comment by preetmishra** [comment]
@zulipbot add "message rendering" "UI" "enhancement"
