### ISSUE TITLE
TRACKING: Topic muting improvements

### ISSUE THREAD

**Issue by preetmishra** [zulip/zulip-terminal#745]
- [ ] Do not show muted topics in stream narrow (and stream unread count)
- [ ] Handle setting unread count for muted topics - #574
- [ ] Support topic muting/unmuting

**Comment by kaustubh-nair** [comment]
@preetmishra I renamed #574 because the PR linked to that issue isn't supposed to handle topic unread counts. It only fixes the bug caused by improper `_found_newest` handling.

**Comment by neiljp** [comment]
Also updating of these topics when topics are re-named (since they're text, not an id)

**Comment by Laanan** [comment]
Hi folks, piggybacking on this issue:

- [ ] allow moving topics to new streams (private to private, private to public, and public to public). 

Also, how can I help? I merely dabble in programming, but is there another way I can contribute to the project?

**Comment by neiljp** [comment]
@Laanan Filing issues is a great start, and if you want more freeform discussion then you're welcome to join #**zulip-terminal** on chat.zulip.org :) Of course you're welcome to contribute in other ways, like with code - there may be some 'good first issue' issues remaining, or just take a dive in the code and see how it works, or figure out how to solve something that's bugging you!
