### ISSUE TITLE
TRACKING: Handle message links

### ISSUE THREAD

**Issue by preetmishra** [zulip/zulip-terminal#764]
- [ ] Handle internal (stream/topic/near narrow) links - #708
- [ ] Handle media (user uploads) links - #740
- [ ] Handle external links

**Comment by zulipbot** [comment]
Hello @preetmishra, you claimed this issue to work on it, but this issue and any referenced pull requests haven't been updated for 10 days. Are you still working on this issue?

If so, please update this issue by leaving a comment on this issue to let me know that you're still working on it. Otherwise, I'll automatically remove you from this issue in 4 days.

If you've decided to work on something else, simply comment `@zulipbot abandon` so that someone else can claim it and continue from where you left off.

Thank you for your valuable contributions to Zulip!

**Comment by Abhirup-99** [comment]
@zulipbot claim.

**Comment by Ezio-Sarthak** [comment]
I would like to add internal PM links handling, as a follow-up PR from #708. Discussed my concerns in czo :)
