### ISSUE TITLE
TRACKING: Support unsubscribed streams

### ISSUE THREAD

**Issue by neiljp** [zulip/zulip-terminal#834]
As of November 2020, the existing code only shows streams subscribed at the time that ZT is loaded; no changes in subscriptions are available to change user subscriptions via a UI or via events affecting the datastructures, during a session.

* [ ] Finish adding defensive checks for cases where events triggered exceptions via non-subscribed streams. These are mostly resolved, though there are a few outstanding cases such as perhaps #816. These need tracking down and the interface to the model data locked down via methods with tests (so the data can be refactored)
* [ ] Refactor the datastructures to include all the streams, and have event handlers update them
* [ ] Have event handlers add/remove subscribed streams (and update UI where appropriate)
* [ ] Add minimal UI to subscribe and unsubscribe from streams

**Comment by mkp6781** [comment]
@zulipbot claim

**Comment by imnitishng** [comment]
I'd like to work on adding the missing streams

**Comment by neiljp** [comment]
There has been some work towards event handling in #851, but refactoring this cleanly can be quite complex.

No code is ready for merging regarding tracking existing unsubscribed streams data, which would be an important starting foundational part of this work.

Some prototype work on a UI was made in #1266, combined with temporary foundational support.
