### ISSUE TITLE
TRACKING: Increase support for widgets (**poll**, todo, trivia, ...)

### ISSUE THREAD

**Issue by neiljp** [zulip/zulip-terminal#986]
This needs careful handling since it is a fairly underdeveloped feature in the server which may change. However it has not changed significantly for some time and `/poll` is now used quite often. On that basis it would be good to be able to:
* [x] View polls which are in messages
* [x] Have polls update as users 'vote'
* [ ] Respond to existing options
* [ ] Add new options

These are in order of extra features - viewing a poll would be a good start, ideally up to date, etc.

Note that there are outstanding issues for elements like `/poll` which don't support markdown, and that the message itself shouldn't be edited (https://github.com/zulip/zulip/issues/17156).

An existing approach applied to the trivia bot is in #287 which could provide a starting point for that particular case (zforms), though it would be good to focus specifically on polls first as they are more common.

For server reference material, see https://zulip.readthedocs.io/en/latest/subsystems/widgets.html

Once we have infrastructure for `/poll` then other similar features should be easier to add.

**NOTE re slash commands in general:**
Note that we already actively support one "command" feature, ie `/me`, and there are more specific commands we could add (shortcuts to settings, setting themes, etc) like in the webapp. However, there has been discussion on splitting no-result commands and commands generating messages into separate UI elements, and we likely don't need slash commands as much in the terminal, at least in the short term.

**Comment by neiljp** [comment]
This issue has been split into other issues for follow-up work and to make it easier to handle, as below, so closing this now.
- #1573 
- #1575 
- #1576 
- #1577
