### ISSUE TITLE
TRACKING: Event handling improvements

### ISSUE THREAD

**Issue by Ezio-Sarthak** [zulip/zulip-terminal#993]
- [ ] #588 : Alert words handling
- [ ] #988 : Update user display settings
- [ ] Update global notifications (currently stream-based priority? #666)
- [ ] #816 Streams (add, delete, update) (#851)
- [ ] #529 Upload/Attachment events
- [ ] Submessages (e.g., polls) (#287)
- [ ] #988: User status updates.
- [ ] Custom profile fields (extension of user info popup #848)
- [ ] Handle Default stream updates (changed by org admin).
- [ ] Delete message event (first event handling, then feature support; #690)
- [ ] User group events (add/modify/delete)
- [ ] #809 : Realm emoji events (#827)

**Comment by Ezio-Sarthak** [comment]
@zulipbot add "area:event handling"

**Comment by zulipbot** [comment]
**ERROR:** Label "area:event handling" does not exist and was thus not added to this issue.

**Comment by Ezio-Sarthak** [comment]
@zulipbot add "area: event handling"

**Comment by neiljp** [comment]
Tagged with GSoC, but this is across multiple areas so as per the tracking nature of this issue, this isn't something one person will likely work on.

**Comment by abhijeetbodas2001** [comment]
> `realm_filters`: Handle a change of configured linkifiers.

I get that this is not a high priority, but whenever in the future ZT adds support for handling events sent after the linkifiers in the realm have changed, we should handle the new `realm_linkifiers` events, since the `realm_filters` event type has been deprecated in feature level 54. #995 has more context. Can you update the issue description?

**Comment by Ezio-Sarthak** [comment]
Thanks! Updated the issue description :)

**Comment by neiljp** [comment]
Also see zulip/zulip-mobile#3408 for a similar mobile tracking issue.
